version: '2'

networks:
  internal:
    external: true

services:
 nexus:
  build: ./nexus
  ports:
    - "18081:8081"
  networks:
    - pgestreamInfrastructure

 jenkins:
  image: jenkinsci/jenkins:lts
  ports:
    - "18080:8080"
  networks:
    - pgestreamInfrastructure
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
    - /var/docker-data/jenkins/:/var/docker-data/lib/jenkins/
  depends_on:
    - nexus
    - sonar
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  networks:
    - pgestreamInfrastructure
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar
 sonardb:
  networks:
    - pgestreamInfrastructure
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
    - /var/docker-data/sonar-db/postgres/data:/var/docker-data/lib/postgresql/data

 
