version: '3'
services:
  service-config:
    build:
      args:
        - no_proxy=$no_proxy,192.168.1.1
        - MIRROR_DEBIAN=http://192.168.1.1/nexus/repository
    env_file:
      - ./dev-config.env
  jenkins:
    build:
      args:
        - no_proxy=$no_proxy,192.168.1.1
        - MIRROR_DEBIAN=http://192.168.1.1/nexus/repository
  gitlab:
    env_file:
      - ./dev-config.env
